### ISSUE TITLE
CodeQL action is failing

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Technology-HuaweiCloud#99]
# Feature Request

CodeQL action is failing on nightly:
https://github.com/eclipse-edc/Technology-HuaweiCloud/actions/runs/11887995581/workflow

> Error calling workflow 'eclipse-edc/.github/.github/workflows/codeql-analysis.yml@main'. The nested job 'analyze' is requesting 'security-events: write', but is only allowed 'security-events: none'.

## Which Areas Would Be Affected?

_e.g., DPF, CI, build, transfer, etc._

## Why Is the Feature Desired?

_Are there any requirements?_

## Solution Proposal

Set the required permission on the CodeQL job call

**Comment by mspiekermann** [comment]
@ndr-brt this is again related to the permissions (like eclipse-edc/.eclipsefdn#26). We will change the workflow accordingly.
